spring:
  application:
    name: tech-blog  # Application name
  datasource:
    url: jdbc:mysql://localhost:3306/tech_blog_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: gusdlr4150!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  batch:
    job:
      enabled: true  # Set to true to enable job auto-start on application startup
    jdbc:
      initialize-schema: always  # Automatically initialize batch metadata tables
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: XXX
            client-secret: XXX
            scope:
              - openid
              - profile
              - email
              - https://www.googleapis.com/auth/drive.metadata.readonly
            redirect-uri: "http://localhost:8888/Callback"
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
